# -*- coding: utf-8 -*-
"""analysis_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AXx8qEVCSytccPyCivWhOnmWl3SC9cz
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset (COLAB version)
df = pd.read_csv("healthcare_data.csv")

sns.set(style="whitegrid")

# -----------------------------
# 1. CONDITION DISTRIBUTION
# -----------------------------
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='condition')
plt.xticks(rotation=45)
plt.title("Condition Distribution")
plt.tight_layout()
plt.savefig("condition_distribution.png")
plt.show()

# -----------------------------
# 2. DOCTOR WORKLOAD
# -----------------------------
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='doctor')
plt.xticks(rotation=45)
plt.title("Doctor Workload")
plt.tight_layout()
plt.savefig("doctor_workload.png")
plt.show()

# -----------------------------
# 3. AGE DISTRIBUTION
# -----------------------------
plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=15, kde=True)
plt.title("Age Distribution")
plt.tight_layout()
plt.savefig("age_distribution.png")
plt.show()

# -----------------------------
# 4. GENDER DISTRIBUTION
# -----------------------------
plt.figure(figsize=(6,4))
sns.countplot(data=df, x='gender')
plt.title("Gender Distribution")
plt.tight_layout()
plt.savefig("gender_distribution.png")
plt.show()

# -----------------------------
# 5. CONDITION VS GENDER
# -----------------------------
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='condition', hue='gender')
plt.xticks(rotation=45)
plt.title("Condition by Gender")
plt.tight_layout()
plt.savefig("condition_gender.png")
plt.show()

print("✅ All images saved successfully!")