# -*- coding: utf-8 -*-
"""analysis_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AXx8qEVCSytccPyCivWhOnmWl3SC9cz
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset (fixed path)
df = pd.read_csv("healthcare_data.csv")

print("📊 Dataset Preview:")
print(df.head())

sns.set(style="whitegrid")

# Condition Distribution
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='condition')
plt.xticks(rotation=45)
plt.title("Condition Distribution")
plt.show()

# Doctor Workload
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='doctor')
plt.xticks(rotation=45)
plt.title("Doctor Workload")
plt.show()

# Age Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=15, kde=True)
plt.title("Age Distribution")
plt.show()