# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDa09ygCP09khcYzRxDAFkuWqIjmZ1iK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("data/healthcare_data.csv")

print("Dataset Preview:")
print(df.head())

# 1. Condition Distribution
plt.figure(figsize=(8,5))
df['condition'].value_counts().plot(kind='bar')
plt.title("Distribution of Medical Conditions")
plt.xticks(rotation=45)
plt.show()

# 2. Gender vs Condition
plt.figure(figsize=(8,5))
sns.countplot(data=df, x='condition', hue='gender')
plt.title("Condition Distribution by Gender")
plt.xticks(rotation=45)
plt.show()

# 3. Age Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['age'], bins=10, kde=True)
plt.title("Age Distribution")
plt.show()

# 4. Doctor Workload
plt.figure(figsize=(8,5))
df['doctor'].value_counts().plot(kind='bar')
plt.title("Appointments per Doctor")
plt.xticks(rotation=45)
plt.show()

# 5. Appointment Types
plt.figure(figsize=(6,6))
df['appointment_type'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Appointment Types")
plt.ylabel("")
plt.show()