# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCQw6saiY9dz9eKHwgVKe-8DuaIaa970
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("🏥 Healthcare Analytics Dashboard")

# Load data
df = pd.read_csv("data/healthcare_data.csv")

# Show data
st.subheader("📊 Dataset Preview")
st.dataframe(df)

# Condition distribution
st.subheader("🦠 Condition Distribution")
condition_counts = df['condition'].value_counts()
st.bar_chart(condition_counts)

# Doctor workload
st.subheader("👨‍⚕️ Appointments per Doctor")
doctor_counts = df['doctor'].value_counts()
st.bar_chart(doctor_counts)

# Age distribution
st.subheader("📈 Age Distribution")
fig, ax = plt.subplots()
df['age'].hist(ax=ax)
st.pyplot(fig)

# Filter option
st.subheader("🔍 Filter by Condition")
selected_condition = st.selectbox("Select Condition", df['condition'].unique())
filtered = df[df['condition'] == selected_condition]
st.write(filtered)