# -*- coding: utf-8 -*-
"""app_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AXx8qEVCSytccPyCivWhOnmWl3SC9cz
"""

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

st.set_page_config(page_title="Healthcare Dashboard", layout="wide")

st.title("🏥 Healthcare Analytics Dashboard")

df = pd.read_csv("data/healthcare_data.csv")

# Sidebar filters
st.sidebar.header("Filters")

condition = st.sidebar.selectbox("Condition", ["All"] + list(df['condition'].unique()))
doctor = st.sidebar.selectbox("Doctor", ["All"] + list(df['doctor'].unique()))

filtered = df.copy()

if condition != "All":
    filtered = filtered[filtered['condition'] == condition]

if doctor != "All":
    filtered = filtered[filtered['doctor'] == doctor]

# Metrics (THIS MAKES IT LOOK PROFESSIONAL)
st.subheader("📊 Key Metrics")

col1, col2, col3 = st.columns(3)
col1.metric("Total Patients", len(filtered))
col2.metric("Unique Conditions", filtered['condition'].nunique())
col3.metric("Doctors", filtered['doctor'].nunique())

# Charts
col1, col2 = st.columns(2)

with col1:
    st.subheader("Condition Distribution")
    fig, ax = plt.subplots()
    sns.countplot(data=filtered, x='condition', ax=ax)
    plt.xticks(rotation=45)
    st.pyplot(fig)

with col2:
    st.subheader("Doctor Workload")
    fig, ax = plt.subplots()
    sns.countplot(data=filtered, x='doctor', ax=ax)
    plt.xticks(rotation=45)
    st.pyplot(fig)

st.subheader("Age Distribution")
fig, ax = plt.subplots()
sns.histplot(filtered['age'], bins=15, kde=True, ax=ax)
st.pyplot(fig)

